scss_files: 'source/assets/styles/**/*.scss'

linters:
    BangFormat:
        enabled: true
        space_before_bang: true
        space_after_bang: false

    BemDepth:
        enabled: true
        max_elements: 2

    BorderZero:
        enabled: true
        convention: none

    ChainedClasses:
        enabled: true

    ColorKeyword:
        enabled: true

    ColorVariable:
        enabled: true

    Comment:
        enabled: true

    DebugStatement:
        enabled: true

    DeclarationOrder:
        enabled: true

    DisableLinterReason:
        enabled: true

    DuplicateProperty:
        enabled: true

    ElsePlacement:
        enabled: true
        style: same_line

    EmptyLineBetweenBlocks:
        enabled: true
        ignore_single_line_blocks: true

    EmptyRule:
        enabled: false # Should be removed by CSS minifiers

    FinalNewline:
        enabled: true
        present: true

    HexLength:
        enabled: true
        style: short

    HexNotation:
        enabled: true
        style: lowercase

    HexValidation:
        enabled: true

    IdSelector:
        enabled: true

    ImportantRule:
        enabled: true

    ImportPath:
        enabled: true
        leading_underscore: false
        filename_extension: false

    Indentation:
        enabled: true
        allow_non_nested_indentation: false
        character: space
        width: 4

    LeadingZero:
        enabled: true
        style: exclude_zero

    MergeableSelector:
        enabled: true
        force_nesting: true

    NameFormat:
        enabled: true
        allow_leading_underscore: true
        convention: hyphenated_lowercase

    NestingDepth:
        enabled: true
        max_depth: 3

    PlaceholderInExtend:
        enabled: tue

    PropertySortOrder:
        enabled: true
        order:
            - content
            - cursor
            - display
            - list-style
            - flex-wrap
            - flex-direction
            - visibility
            - opacity
            -
            - float
            - z-index
            - position
            - left
            - right
            - top
            - bottom
            - transform
            -
            - width
            - min-width
            - max-width
            - height
            - min-height
            - max-height
            -
            - margin
            - margin-left
            - margin-right
            - margin-top
            - margin-bottom
            - padding
            - padding-left
            - padding-right
            - padding-top
            - padding-bottom
            -
            - outline
            - border
            - border-style
            - border-width
            - border-color
            - border-radius
            - background
            - background-color
            - background-image
            - background-position
            - background-size
            - background-repeat
            -
            - white-space
            - text-transform
            - font-size
            - font-weight
            - line-height
            - color
            -
            - transition
            - animation
        separate_groups: true

    PropterySpelling:
        enabled: true

    PropertyUnits:
        enabled: true
        global: ['em', 'rem', '%', 'vw', 'vh', 's']

    PseudoElement:
        enabled: true

    QualifyingElement:
        enabled: true
        allow_element_with_attribute: true
        allow_element_with_class: false
        allow_element_with_id: false

    SelectorDepth:
        enabled: true
        max_depth: 3

    SelectorFormat:
        enabled: true
        convention: hyphenated_BEM

    SingleLinePerProperty:
        enabled: true
        allow_single_line_rule_sets: true

    SingleLinePerSelector:
        enabled: true

    SpaceAfterComma:
        enabled: true
        style: one_space

    SpaceAfterPropertyColon:
        enabled: true
        style: one_space

    SpaceAfterPropertyName:
        enabled: true

    SpaceAfterVariableName:
        enabled: true

    SpaceAroundOperator:
        enabled: true
        style: one_space

    SpaceBeforeBrace:
        enabled: true
        allow_single_line_padding: false
        style: space

    SpaceBetweenParens:
        enabled: true
        spaces: 0

    StringQuotes:
        enabled: true
        style: single_quotes

    TrailingSemicolon:
        enabled: true

    TrailingWhitespace:
        enabled: true

    TrailingZero:
        enabled: true

    TransitionAll:
        enabled: true

    UnnecessaryMantissa:
        enabled: true

    UnnecessaryParentReference:
        enabled: true

    UrlFormat:
        enabled: true

    UrlQuotes:
        enabled: true

    VariableForProperty:
        enabled: true
        properties:
            - color
            - font

    VendorPrefix:
        enabled: true
        identifier_list: base

    ZeroUnit:
        enabled: true
